[package]
version = "0.1.0"
name = "fibonacci-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = { path = "../../../../crates/zkvm/entrypoint" }
fibonacci-lib = { path = "../lib" }
